version: "3"
#############################
#                           #
# SUPERTANK SCRAPER WEBSITE #
#                           #
#############################
services:
  supertank-scraper-website:
    image: "tuncaya/supertank-scraper-website:latest"
    build:
      context: .
      dockerfile: Dockerfile
    hostname: supertank-scraper-website
    container_name: supertank-scraper-website
    tty: true
    ports:
      - '9821:80'
    restart: unless-stopped
#    labels:
#      - "com.centurylinklabs.watchtower.enable=false"
